baseURL = "http://example.org/"
languageCode = "en-us"
title = "TUI"
theme = "tui"


# Navigation ##############################
# main menu
[[menu.main]]
name = "TUI"
url = "/#tui"
weight = 1

[[menu.main]]
name = "Get start"
url = "/#start"
weight = 2

[[menu.main]]
name = "Layous"
url = "/#layouts"
weight = 3

[[menu.main]]
name = "Grids"
url = "/#grids"
weight = 4

[[menu.main]]
name = "Menus"
url = "/#menus"
weight = 5

[[menu.main]]
name = "Tables"
url = "/#tables"
weight = 6

[[menu.main]]
name = "Buttons"
url = "/#buttons"
weight = 7

[[menu.main]]
name = "Icons"
url = "/#icons"
weight = 8

[[menu.main]]
name = "Images"
url = "/#images"
weight = 9

[[menu.main]]
name = "List"
url = "/#list"
weight = 10

[[menu.main]]
name = "Forms"
url = "/#forms"
weight = 11
